enabled: true
checking_period_ticks: 1
checking_distance_override: -1
checking_amounts_per_period: 50

bounding_box_extra_value: 0.1
sample_points: 8
perspective_checking:
  enabled: true
  distances: 4
