enabled: true
debug: false
checking_period_ticks: 1
checking_distance_override: 5

bounding_box_extra_value: 0.5
vertices_layers: 5
perspective_checking:
  enabled: true
  distances_from_head: 4
fake_name_display:
  enabled: true
  period_ticks: 1

anti_entities:
- player
anti_mode: whitelist
