main: ${main}
api-version: ${apiVersion}

name: ${name}
version: ${version}
author: ${author}
description: ${description}

softdepend: [PlaceholderAPI]

permissions:
  raytrace_anti_entity_esp.admin:
    default: op
  raytrace_anti_entity_esp.bypass:
    default: false

commands:
  raytrace_anti_entity_esp:
    permission: raytrace_anti_entity_esp.admin
    aliases: [rtaee, raytraceantientityesp]
    description: Main command for RayTraceAntiEntityESP plugin
    usage: /<command>
